### PR TITLE
Feat/entry point

### PR DESCRIPTION
**Pull request by omangin**
Needs to double check for auto-completion. (See also #110.)

### CODE REVIEW

**Comment by omangin** [comment]
OK, I added it to `pubs_cmd.py`. That should do the job. Can you double check that it work?

I also noticed that the global completion does not seem to work when the package is installed in `develop` mode. In which case on needs to execute the `eval "$(register-python-argcomplete pubs)"`. Might be related to [argcomplete/#112](https://github.com/kislyuk/argcomplete/issues/112) that was apparently fixed but not in the latest version. It's minor though, so I am just putting it there for the record.

**Comment by omangin** [comment]
Great. I'll merge then. Do you have `eval "$(register-python-argcomplete pubs)"` somewhere in your path or are you using the global completion mode?

**Comment by wflynny** [comment]
@omangin  Hmm in a brand new environment, you're right; it doesn't work in `develop` mode.  But I can't seem to find where in my normal test environment `eval "$(register-python-argcomplete pubs)"`.  For example, in both environments, this is all I have under `complete`.

```
(pubs-test)$ complete -p
complete -o bashdefault -o default -F _python_argcomplete_global -D
```

In my bash history, I do have `eval $"(register-python-argcomplete pubs)"`, but I'm not sure where to look for it's effects other than `complete`/`env`.  Using bash `version 4.4.12(1)-release (x86_64-apple-darwin16.3.0)`.

Should we open this up as a new bug?

**Comment by omangin** [comment]
So if it sets the completion for `pubs`, it should show up in `complete | grep pubs`. Otherwise it is using the global mode that is active for you (as shown in the output you pasted above).

In any case, since it is working in `install` mode, this is not a pubs issue but eventually an upstream bug on `argcomplete`. However they seemed to have merged some things related to that that is not yet in the latest available version so it's probably already fixed.

**Pull request merged**
