### PR TITLE
feature #19

### PR DESCRIPTION
**Pull request by 73**
not that I need this feature, but i like this project. :)

### CODE REVIEW

**Comment by 73** [comment]
I missed a test...

**Comment by humm** [comment]
Hi, nice work. Glad you like the project. 

Just a heads-up, the new config code is progressing, it's here: [feat/new_config](/pubs/pubs/tree/feat/new_config). I need to polish it a bit more before I merge it into master, but it will happen soon.

**Comment by 73** [comment]
I will rebase against feat/new_config. I think that makes the most sense.

**Comment by humm** [comment]
Probably best. A commit just came your way.

**Pull request closed without merging**
