### PR TITLE
Version 0.8.0.

### PR DESCRIPTION
**Pull request by omangin**

### CODE REVIEW

**Comment by omangin** [comment]
@benureau Please release if everything is good to go!

**Comment by benureau** [comment]
@omangin: so, I know what I said, but don't you think it would be reaaally nice to have support for arXiv in the release? It's a matter of days now.

**Comment by benureau** [comment]
@omangin: If you merge everything and want to release right after, go ahead.

**Comment by omangin** [comment]
Yes, let's just do it as soon as #155 and #159 are merged.

**Comment by omangin** [comment]
@benureau We should be good to go. The tests are however failing on the current master of [python-bibtexparser](https://github.com/sciunto-org/python-bibtexparser) but I guess this is related to [bibtexparser/#211](https://github.com/sciunto-org/python-bibtexparser/issues/211). Do you believe this is an issue for releasing this?

**Comment by benureau** [comment]
@omangin: no, since users are going to use the latest release of bibtexparser, unless they installed the development version, and then, they should expect issues.

**Pull request merged**
