### PR TITLE
Detect HTTPS links in content_type()

### LINKED ISSUE #258: Download file if link is passed to `pubs doc add`
It would be great if `pubs` downloaded the file if a link was passed to `pubs doc add`. Example:

```bash
pubs doc add https://link.to/paper.pdf Citation_Key
```

Best regards,
Gustavo Sousa

### PR DESCRIPTION
**Pull request by guludo**
Hi there,

This allows downloading files provided via https links.

This PR fixes #258 .

Best regards,
Gustavo Sousa

### CODE REVIEW

**Comment by benureau** [comment]
It's a simple but critical improvement. I would prefer having a test for this, but I am not sure that downloading a file of the internet with unit test is a good idea. I will look into it.

**Comment by omangin** [comment]
>  I would prefer having a test for this, but I am not sure that downloading a file of the internet with unit test is a good idea.

Let's add first a simple unit test for the `content_type` method that the PR changes. Then is should be feasible to just mock the `urlopen` imported in the module to get a functional test that does not rely on an internet connection.

**Comment by benureau** [comment]
@guludo: I am merging this (sorry for the delay!). I will add a test for it, but I am decoupling that from merging this. See #271.

**Comment by guludo** [comment]
No worries! And thanks for applying. Sorry I couldn't help writing tests for it.

**Pull request merged**
