### PR TITLE
adds a *doc* command

### PR DESCRIPTION
**Pull request by 73**
adds a *doc add|remove|export|open* command; depricates commands *ope…

### CODE REVIEW

**Comment by humm** [comment]
Looks good. I'll test it today.

**Comment by 73** [comment]
The commit got automatically appended. Didn't expect that.

**Comment by humm** [comment]
Yep, that's how pull requests work. You should use a different branch name for different features. For this one, we'll consider both features together. Tell us when it is ready to be reviewed.

**Comment by 73** [comment]
I will. But why the encode test failed remains a mystery to me. :/ I'll fix that and let you know, when it's done.

**Comment by humm** [comment]
No that's ok. See #40.

**Comment by 73** [comment]
Ah. puuuuuhhhh... I thought it was me...

**Comment by 73** [comment]
Okay done. This implements:
+ Prefix completion for #34 
+ The `doc` command for #41 
+ And completely closes #43 
Done for now...        
--73

**Comment by humm** [comment]
I just tested everything. Fantastic work. Really pushes the project forward.

**Comment by 73** [comment]
Thanks. I'll implement what I feel, I do need. ;)

**Pull request merged**
