### PR TITLE
Feat/autocomplete

### PR DESCRIPTION
**Pull request by omangin**
Basic implementation of shell autocompletion with argcomplete (see #34). Any testing, suggestion, or comment is welcome.

Note: the tests are failing on python2 due to #58.

### CODE REVIEW

**Comment by benureau** [comment]
So I tried to make it work, but there are a few issues on macOS, one of them being that bash is outdated. I have upgraded bash, made it the login shell, and some other voodoo stuff, and I have made it work. On the plus side, having it not work does not seem to affect the other behavior of pubs so that's that. I'll add a few words for macOS users in the readme.

The command `open` does not seem to have completion enabled (I have not look into the code yet). It is slow: can it be avoided by using caches?

**Comment by omangin** [comment]
Great! The open command does not exist anymore and you probably have it set as an alias to `doc open`. Aliases are not supported yet so that's why it does not work.

Regarding the speed, the completion already uses the cache. On my computer with 500 papers it's quite OK though (<0.5s). The eventual delay comes from
– what is loaded before [the `autocomplete` command](https://github.com/pubs/pubs/blob/feat/autocomplete/pubs/pubs_cmd.py#L86). I'm not sure we have such a big margin to optimize there,
– the command to get the list of citekeys which currently lists the content of the directory (see the `databroker`). This could be replaced by a cached list of citekeys and a check to the directory last modified date but I'm not sure it would save much time.
In any case we should profile it first.
The tag completion is slower because it requires loading the metatdata from all papers in the repository. We could implement caching the tags at directory level but it would still require (if we want to keep accuracy) that all metadata are checked for update. Once again, I'm not sure it worth it.

**Comment by benureau** [comment]
Hum... I have 900 papers and it's more like ~1s on mine (SSD and all). I'll look into it, I feel that there are some low-hanging fruits here on speed. But it's a different issue. I'll try to add the setup instructions soon.

**Comment by omangin** [comment]
> I'll try to add the setup instructions soon.
There are already some in the `readme` but they might benefit some additions.

**Comment by omangin** [comment]
BTW, here are the times I get for loading the main components of pubs in `ipython` with `%time`:
- 47 ms for `from pubs.ui import get_ui`
- 2 ms for `get_ui()`
- 13 us for `from pubs import config`
- 12 us for `config.get_confpath(verify=False)`
- 778 us for `load_conf(conf_path)`
- 90 us for `repo.Repo(conf)`
- 3 ms for `rp.citekeys`
- 85 ms for `rp.get_tags`

So it does not seem that any of them is critically slow  (thanks to the cache for the last two, which as a matter of fact are the only ones that should scale with the size of the repository). The overall time seems to match what I experience (with some additional `argparse` and `argcomplete` overhead). 

@benureau Maybe you could check if you get the same times on your machine.

If we cannot solve the speed this time and it's the only issue with the PR, I'd suggest we merge anyway, mark completion as experimental, and open a new issue to get more feedback.

**Comment by benureau** [comment]
Ok. Created #72 to deal with the speed. Merging this.

**Pull request merged**
